# Generated by Django 6.0.3 on 2026-04-02 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(default='Minha Empresa', max_length=150)),
                ('nome_sistema', models.CharField(default='Sistema de Estoque', max_length=150)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('cor_primaria', models.CharField(default='#2563eb', max_length=20)),
                ('cor_secundaria', models.CharField(default='#0f172a', max_length=20)),
                ('cor_fundo', models.CharField(default='#eef2f7', max_length=20)),
                ('cor_texto', models.CharField(default='#0f172a', max_length=20)),
                ('fonte_base', models.CharField(default='Inter', max_length=50)),
                ('tamanho_fonte_base', models.IntegerField(default=15)),
                ('tamanho_logo', models.IntegerField(default=44)),
                ('raio_borda', models.IntegerField(default=20)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
