# Generated by Django 6.0.3 on 2026-04-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='cor_botao_perigo',
            field=models.CharField(default='#ef4444', max_length=20),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='cor_card',
            field=models.CharField(default='#ffffff', max_length=20),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='exibir_subtitulo_empresa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='largura_container',
            field=models.IntegerField(default=1500),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='layout_compacto',
            field=models.BooleanField(default=False),
        ),
    ]
