# Generated by Django 6.0.3 on 2026-04-04 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentacaoestoque',
            options={},
        ),
        migrations.RenameField(
            model_name='movimentacaoestoque',
            old_name='criado_em',
            new_name='data',
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('AJUSTE', 'Ajuste'), ('REPOSICAO', 'Reposição')], max_length=20),
        ),
    ]
