# Generated by Django 6.0.3 on 2026-04-02 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacaoArquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='importacoes/')),
                ('tipo_arquivo', models.CharField(choices=[('PDF', 'PDF'), ('XLSX', 'Excel'), ('CSV', 'CSV')], max_length=10)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSADO', 'Processado'), ('ERRO', 'Erro')], default='PENDENTE', max_length=20)),
                ('total_registros', models.PositiveIntegerField(default=0)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
